framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # Les notifications (chat / sms) restent asynchrones
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # En retirant le routing pour App\Message\ContactMessage, il sera traité immédiatement (synchrone)

            # IMPORTANT: On ne route plus SendEmailMessage vers async pour que l'envoi email
            # se fasse directement dans le handler (pas de double file d'attente).
